### ISSUE TITLE
Cannot assign to read only property of object

### ISSUE THREAD

**Issue by kenjonespizza** [WHenderson/svelte-immer-store#4] opened 2022-06-25 00:54 UTC
#### Description:
Hi!  First off, thanks for making this package!  I've run into something that I'm assuming is a bug, but very much could just be me.

In this REPL you can see the value of the store(obj) cannot be assigned. `Error: Cannot assign to read only property 'foo' of object`.
REPL: [https://svelte.dev/repl/681913c9050b48a794e9133664c370db?version=3.23.2](https://svelte.dev/repl/681913c9050b48a794e9133664c370db?version=3.23.2
)

It does work with writable store: [https://svelte.dev/repl/43e3eade9ec840dab9ab3a5177aa0dfa?version=3.23.2](https://svelte.dev/repl/43e3eade9ec840dab9ab3a5177aa0dfa?version=3.23.2)

Thanks!

**Comment by WHenderson** [comment] 2022-06-29 12:55
If you want read/write access to a sub property you will need to create a sub store. 

Something like:
 ```
const foo = store.select(root => root['foo']);
```
and then bind to the new store.

**Comment by kenjonespizza** [comment] 2022-07-06 00:48
@WHenderson Thanks for the response.

However... I can't seem to get it working or wrap my head around why it's not working.

I can't use your exact solution above, because I don't know what the var will be called, because the key/values are going to be loaded i from a database in my app.  I made a new REPL with your fix of selecting the sub store, and I'm still getting the same error.

REPL: https://svelte.dev/repl/6dfe4b196ae8478faef1db02883caddf?version=3.23.2

I'm trying to update the `$contents` store now in the REPL

Thanks for any advice :)
- Ken

**Comment by WHenderson** [comment] 2022-07-06 04:07
Immer objects need to be updated using a production. When you try to assign to a sub-property of an immer object, it errors out because that's not allowed.

Instead, to update a sub-property, you need to create an explicit store using one of the `.select` overloads.

If the only problem with creating a substore is that you don't know what the key will be called, you can just use one of the `.select` functions with a variable specifying the subkey instead of a constant.
If the problem is that you need to dynamically create a set of references, that gets more tricky as svelte still doesn't support making/using stores on the fly. Instead you'll need to create a sub-component.

I'm sure that sentence is a little impenetrable so here is an example: https://svelte.dev/repl/6781f7d9dd224995885d59a77b72bbc7?version=3.23.2

Note that the `Sub.svelte` component is now the one creating the dynamic sub-store.

Hope this helps.

**Closed as completed** 2024-11-07 02:47 UTC
